sudo: required

language: go

go:
  - 1.7.3

before_install:
  - env
  - make glide

install:
  - make deps

before_script:
  - export PATH=$HOME/gopath/bin:$PATH

script:
  - make test
  - make

after_script:

addons:
  artifacts:
    paths:
      - $(git ls-files -o --exclude-standard | tr "\n" ":")
    debug: true
    bucket: game-image-dev
    target-paths: artifacts/$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH
  s3_region: "ap-northeast-1"
