language: go

go:
  - 1.7.5

before_install:
  - make glide

install:
  - make deps

before_script:
  - export PATH=$HOME/gopath/bin:$PATH
  - make fmt
  - make imports
  - make lint
  - make vet
  - make test

script:
  - make

after_script:

addons:
  artifacts:
    s3_region: "ap-northeast-1"
    paths:
      - $(git ls-files -o --exclude-standard | tr "\n" ":")
    debug: true
    target-paths: artifacts/$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH
